"""Incident persistence, triage orchestration and versioned response integration."""

from __future__ import annotations

import uuid
from datetime import datetime, timezone
from decimal import Decimal

from sqlalchemy.orm import Session

from app.models.incident import (
    Incident,
    IncidentStatus,
    IncidentType,
    OtherCrimeSubCategory,
    PaymentMethod,
    Urgency,
)
from app.schemas.incident import (
    ActionItem,
    ActionPlanResponse,
    ComplaintDraft,
    IncidentCreate,
    TriageRequest,
    IncidentDetailsUpdate,
)
from app.domain.facts import FACTS_ADAPTER
from app.domain.playbooks import evaluate
from app.domain.response import ResponsePlan
from app.domain.sources import source
from app.services import response_service
from app.services.incident_presentation import (
    CORE_MESSAGES, INCIDENT_TYPE_LABELS, MISSING_UTR_TEXT,
    OTHER_CRIME_SUB_CATEGORY_LABELS, PAYMENT_METHOD_LABELS, URGENCY_BADGE,
    _as_float, _as_utc, format_inr, format_occurred_at, render_complaint_draft,
)
from app.services.legacy_incident_service import (
    build_category_action_plan, compute_other_cyber_urgency, compute_women_children_urgency,
)
from app.domain.policy import check_values
from app.rules.action_rules import determine_other_cyber_plan, determine_women_children_plan
from app.rules.constants import AMOUNT_THRESHOLDS


HELPLINE_1930 = "1930"
CYBERCRIME_PORTAL_URL = source("NCRP-REPORT").official_url
BANK_HELPLINE_PLACEHOLDER = "the number on the back of your card / in your bank app"

# Internal financial-impact metadata only; never a reporting/FIR threshold.
LARGE_AMOUNT_THRESHOLD = float(AMOUNT_THRESHOLDS["very_high"])

# Product heuristics, intentionally separate from the financial-fraud clock.


# Deprecated compatibility data, generated by the canonical engine rather than
# maintaining a second financial decision table. No current route uses this table.
def build_action_list(urgency: Urgency, payment_method: PaymentMethod, *, large_amount: bool = False) -> list[ActionItem]:
    facts = FACTS_ADAPTER.validate_python({"kind": "financial_authorization_unknown", "payment_method": payment_method})
    plan = evaluate(facts, as_of=datetime(2026, 10, 1, tzinfo=timezone.utc))
    return [a.model_copy(update={"priority": urgency}) for a in plan.actions]

ACTION_PLAN_RULES = {(u, p): tuple(build_action_list(u, p)) for u in Urgency for p in PaymentMethod}
_RULE_ACTIONS = {a.id: a for a in build_action_list(Urgency.high, PaymentMethod.unknown)}

# --- Pure functions (unit-tested) --------------------------------------------


def is_large_amount(amount: float | Decimal | None) -> bool:
    value = _as_float(amount)
    if value is None:
        return False
    return value >= LARGE_AMOUNT_THRESHOLD


def compute_urgency(
    occurred_at: datetime,
    amount: float | Decimal | None,
    *,
    now: datetime | None = None,
) -> Urgency:
    """Deprecated compatibility helper; delegates to the versioned financial engine."""
    facts = FACTS_ADAPTER.validate_python({"kind": "financial_authorization_unknown", "occurred_at": occurred_at, "amount": amount})
    return evaluate(facts, as_of=now or datetime.now(timezone.utc)).urgency


def build_action_plan(incident: Incident, *, db: Session) -> ActionPlanResponse:
    if incident.incident_type in {IncidentType.women_children, IncidentType.other_cyber_crime}:
        return build_category_action_plan(incident)
    recorded = response_service.latest(db, incident.id)
    if recorded is None:
        raise ValueError("No versioned financial plan recorded")
    plan = ResponsePlan.model_validate(recorded.plan)
    if plan.facts.kind == 'incident_understanding':
        body = 'WORKING INCIDENT NOTES — review before using on an external official service.\n'
        body += 'Financial loss: ' + ('No known loss reported' if plan.facts.money_lost is False else 'Unknown') + '\n'
        body += 'Possible signals: ' + (', '.join(plan.facts.signals) or 'Still gathering information') + '\n'
        body += 'These interpreted details require your review. Preparing notes does not submit a complaint.'
        return ActionPlanResponse(urgency=plan.urgency, urgency_label='Still gathering information',
            core_message='Review your working understanding and applicable steps. Classification remains provisional.',
            large_amount=False, actions=list(plan.actions), complaint_draft=ComplaintDraft(body=body),
            playbook_id=plan.playbook_id, playbook_version=plan.playbook_version,
            fact_schema_version=plan.fact_schema_version, plan_revision=recorded.revision, urgency_reasons=[])
    body = render_complaint_draft(incident_type=incident.incident_type,
        occurred_at=plan.facts.occurred_at, amount=plan.facts.amount,
        payment_method=plan.facts.payment_method, transaction_id=plan.facts.transaction_id,
        urgency=plan.urgency, actions=list(plan.actions))
    body += "\nPayment authorization stated: " + {"authorized": "approved after deception", "unauthorized": "not authorized", "unknown": "unknown"}[plan.facts.authorization]
    return ActionPlanResponse(urgency=plan.urgency, urgency_label=URGENCY_BADGE[plan.urgency],
        core_message=CORE_MESSAGES[plan.urgency], large_amount=is_large_amount(plan.facts.amount),
        actions=list(plan.actions), complaint_draft=ComplaintDraft(body=body),
        playbook_id=plan.playbook_id, playbook_version=plan.playbook_version,
        fact_schema_version=plan.fact_schema_version, plan_revision=recorded.revision,
        urgency_reasons=[{"factor": "playbook", "rule_id": plan.playbook_id + "-" + plan.playbook_version,
            "human_readable_reason": r, "severity_contribution": plan.urgency.value} for r in plan.reasons])


# --- Persistence -------------------------------------------------------------


def update_description(db: Session, incident: Incident, description: str) -> Incident:
    check_values(description)
    incident.description = description
    db.commit()
    db.refresh(incident)
    return incident


def generate_summary(incident: Incident):
    from app.services.incident_summary import generate_incident_summary
    from app.schemas.evidence import GenerateSummaryResponse
    draft, provider = generate_incident_summary(incident=incident, user_description=incident.description or "")
    return GenerateSummaryResponse(draft=draft, provider=provider)


def create_incident(db: Session, payload: IncidentCreate) -> tuple[Incident, str]:
    check_values(payload.model_dump(mode="json"))
    incident = Incident(
        incident_type=payload.incident_type,
        payment_method=payload.payment_method,
        amount=payload.amount,
        incident_time=payload.incident_time,
        occurred_at=payload.incident_time,
        other_crime_sub_category=payload.other_crime_sub_category,
        details=payload.details,
        incident_subtype=payload.incident_subtype,
        affected_person_type=payload.affected_person_type,
        platform=payload.platform,
        account_type=payload.account_type,
        immediate_danger=payload.immediate_danger,
        threat_or_blackmail=payload.threat_or_blackmail,
        content_still_online=payload.content_still_online,
        account_access=payload.account_access,
        attacker_active=payload.attacker_active,
        sensitive_information_exposed=payload.sensitive_information_exposed,
        evidence_types=payload.evidence_types,
        urgency=Urgency.medium,
        status=IncidentStatus.draft,
    )
    from app.services.case_access import issue
    token = issue(incident)
    db.add(incident)
    db.flush()
    if payload.conversation_first or incident.incident_type == IncidentType.financial_fraud:
        facts = FACTS_ADAPTER.validate_python({"kind": "incident_understanding" if payload.conversation_first else "financial_authorization_unknown", "amount": payload.amount,
            "occurred_at": payload.incident_time, "payment_method": payload.payment_method})
        response_service.record_plan(db, incident, facts, as_of=datetime.now(timezone.utc))
        incident.status = IncidentStatus.draft
    else:
        incident.playbook_id = "legacy_nonfinancial"
    db.commit()
    db.refresh(incident)
    return incident, token


def get_incident(db: Session, incident_id: uuid.UUID) -> Incident | None:
    return db.get(Incident, incident_id)


def update_incident_details(
    db: Session, incident: Incident, payload: IncidentDetailsUpdate
) -> Incident:
    check_values(payload.model_dump(mode="json"))
    incident.other_crime_sub_category = payload.other_crime_sub_category
    incident.details = payload.details
    db.commit()
    db.refresh(incident)
    return incident


def triage_incident(
    db: Session,
    incident: Incident,
    payload: TriageRequest,
    *,
    now: datetime | None = None,
) -> Incident:
    clock = _as_utc(now or datetime.now(timezone.utc))
    check_values(payload.model_dump(mode="json"))
    occurred_at = _as_utc(payload.occurred_at) if payload.occurred_at else None
    incident.incident_type = payload.incident_type
    incident.occurred_at = occurred_at
    incident.incident_time = occurred_at
    incident.amount = payload.amount
    incident.payment_method = payload.payment_method
    incident.transaction_id = payload.transaction_id
    incident.transaction_status = payload.transaction_status
    incident.is_fraud_ongoing = payload.is_fraud_ongoing
    incident.is_account_compromised = payload.is_account_compromised
    incident.is_credentials_exposed = payload.is_credentials_exposed
    incident.is_otp_shared = payload.is_otp_shared
    incident.is_pin_shared = payload.is_pin_shared
    incident.is_password_shared = payload.is_password_shared
    incident.is_remote_access_granted = payload.is_remote_access_granted
    incident.unauthorized_activity_continuing = payload.unauthorized_activity_continuing
    incident.potential_additional_loss = payload.potential_additional_loss
    incident.account_secured = payload.account_secured
    incident.evidence_available = payload.evidence_available
    incident.other_crime_sub_category = payload.other_crime_sub_category
    incident.details = payload.details
    incident.incident_subtype = payload.incident_subtype
    incident.affected_person_type = payload.affected_person_type
    incident.platform = payload.platform
    incident.account_type = payload.account_type
    incident.immediate_danger = payload.immediate_danger
    incident.threat_or_blackmail = payload.threat_or_blackmail
    incident.content_still_online = payload.content_still_online
    incident.account_access = payload.account_access
    incident.attacker_active = payload.attacker_active
    incident.sensitive_information_exposed = payload.sensitive_information_exposed
    incident.evidence_types = payload.evidence_types
    if payload.incident_type == IncidentType.financial_fraud:
        def known_any(*values):
            return True if any(v is True for v in values) else None if any(v is None for v in values) else False
        kind = {"authorized": "financial_scam_transfer", "unauthorized": "unauthorized_financial_transaction", "unknown": "financial_authorization_unknown"}[payload.authorization]
        facts = FACTS_ADAPTER.validate_python({"kind": kind, "occurred_at": occurred_at,
            "amount": payload.amount, "payment_method": payload.payment_method,
            "transaction_id": payload.transaction_id, "transaction_status": payload.transaction_status,
            "account_compromised": payload.is_account_compromised, "remote_access": payload.is_remote_access_granted,
            "credentials_exposed": known_any(payload.is_credentials_exposed, payload.is_otp_shared, payload.is_pin_shared, payload.is_password_shared),
            "ongoing_loss": known_any(payload.is_fraud_ongoing, payload.unauthorized_activity_continuing, payload.potential_additional_loss),
            "evidence_available": payload.evidence_available})
        record = response_service.record_plan(db, incident, facts, as_of=clock)
        urgency, score = incident.urgency, None
        incident.urgency_reasons = [{"factor": "playbook", "rule_id": incident.playbook_id + "-" + incident.playbook_version,
            "human_readable_reason": reason, "severity_contribution": urgency.value} for reason in record.plan["reasons"]]
    elif payload.incident_type == IncidentType.women_children:
        category_plan = determine_women_children_plan(payload.incident_subtype, payload.affected_person_type, payload.immediate_danger, payload.threat_or_blackmail, payload.content_still_online, payload.details)
        urgency, score = category_plan.priority, compute_women_children_urgency(incident, now=clock)[1]
        incident.severity = category_plan.severity
        incident.ongoing_risk = category_plan.ongoing_risk
        incident.recovery_window = None
        incident.urgency_reasons = category_plan.reasons
    elif payload.incident_type == IncidentType.other_cyber_crime and payload.incident_subtype:
        category_plan = determine_other_cyber_plan(payload.incident_subtype, payload.account_access, payload.attacker_active, payload.sensitive_information_exposed, payload.details)
        urgency, score = category_plan.priority, compute_other_cyber_urgency(incident, now=clock)[1]
        incident.severity = category_plan.severity
        incident.ongoing_risk = category_plan.ongoing_risk
        incident.recovery_window = None
        incident.urgency_reasons = category_plan.reasons
    else:
        urgency, score = Urgency.medium, None
    incident.urgency = urgency
    incident.urgency_score = score
    incident.urgency_computed_at = clock
    incident.status = IncidentStatus.action_required

    db.commit()
    db.refresh(incident)
    return incident
