const assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_PACKAGE||'playwright');
const base=process.env.SMOKE_FRONTEND_URL, api=process.env.SMOKE_API_URL;
(async()=>{
  const browser=await chromium.launch({headless:true});
  try{
    const context=await browser.newContext({viewport:{width:1280,height:900}}),page=await context.newPage();
    page.setDefaultTimeout(20000);await page.goto(base);
    await page.getByRole('link',{name:'Tell us what happened',exact:true}).click();
    await page.waitForURL('**/incident/start');
    await page.getByRole('heading',{name:'Tell us what happened',exact:true}).waitFor();
    assert.equal(await page.getByRole('button',{name:'Money is gone'}).count(),0);
    async function send(text){await page.getByRole('textbox',{name:'Message CyberSOS'}).fill(text);
      const result=page.waitForResponse(r=>r.url().endsWith('/conversation/turns'));
      await page.getByRole('button',{name:'Send message',exact:true}).click();
      const response=await result;assert.equal(response.status(),200);const state=await response.json();
      await page.waitForURL(/\/incident\/[^/]+\/conversation$/);
      await page.getByRole('list',{name:'Saved message history'}).getByText(text,{exact:true}).waitFor();
      return state;}
    let state=await send('₹5,000 left my account without my approval.');
    assert.equal(state.turns.length,1);assert.equal(state.facts.authorization,'unauthorized');
    assert.equal(await page.getByRole('heading',{name:'ACT NOW',exact:true}).count(),0); // Unknown timing is not urgency.
    const path=api+'/api/v1/incidents/'+state.incident_id+'/conversation';
    assert.equal((await(await context.request.get(path)).json()).turns.length,1);
    const composer=page.getByRole('textbox',{name:'Message CyberSOS'});
    await composer.fill('A draft stays here');await page.getByRole('button',{name:'View case',exact:true}).click();
    assert.equal(await composer.inputValue(),'A draft stays here');
    await page.getByRole('complementary',{name:'Current case details'}).waitFor();
    await page.getByRole('button',{name:'Close details'}).click();
    state=await send('It happened about an hour ago.');
    await page.getByRole('heading',{name:'ACT NOW',exact:true}).waitFor();
    state=await send('Sorry, it was ₹4,500.');assert.equal(state.facts.amount,'4500');
    await page.reload();await page.getByRole('list',{name:'Saved message history'}).getByText('Sorry, it was ₹4,500.',{exact:true}).waitFor();
    assert.equal((await(await context.request.get(path)).json()).memory.facts.amount.value,'4500');
    for(const size of [{width:390,height:844},{width:390,height:420}]){
      await page.setViewportSize(size);await composer.fill('draft\nline two\nline three');
      await page.getByRole('button',{name:'View case',exact:true}).click();
      const rectangle=await composer.boundingBox();assert.ok(rectangle.y>=0&&rectangle.y+rectangle.height<=size.height);
      const composerTop=rectangle.y;const sheet=await page.getByRole('complementary',{name:'Current case details'}).boundingBox();
      assert.ok(sheet.y+sheet.height<=composerTop||sheet.x>=rectangle.x+rectangle.width,'Artifact must not obscure composer');
      await page.getByRole('button',{name:'Close details'}).click();assert.equal(await composer.inputValue(),'draft\nline two\nline three');
    }
    await composer.fill('');
    const picker=page.locator('input[type=file]');
    await picker.setInputFiles({name:'synthetic.pdf',mimeType:'application/pdf',buffer:Buffer.from('%PDF-1.4\nSynthetic\n%%EOF')});
    await page.getByText('Ready to send · not analyzed',{exact:true}).waitFor();
    const posted=page.waitForResponse(r=>r.url().endsWith('/conversation/turns'));
    await page.getByRole('button',{name:'Send message',exact:true}).click();state=await(await posted).json();
    assert.equal(state.turns.at(-1).text,'');assert.equal(state.turns.at(-1).attachments.length,1);
    await page.getByRole('link',{name:'Open attachment',exact:true}).waitFor();
    await page.reload();await page.getByRole('link',{name:'Open attachment',exact:true}).waitFor();
    const attachmentId=state.turns.at(-1).attachments[0].id;
    const outsider=await browser.newContext();assert.equal((await outsider.request.get(api+'/api/v1/evidence/'+attachmentId+'/file')).status(),404);await outsider.close();
    const replay=await context.request.post(path+'/turns',{data:state.turns.at(-1).structured_reply});assert.equal(replay.status(),200);
    assert.equal((await replay.json()).turns.length,state.turns.length);
    await page.getByRole('button',{name:'Delete attachment',exact:true}).click();await page.getByText('Attachment deleted',{exact:true}).waitFor();
    await page.setViewportSize({width:390,height:844});
    state=await send('I also installed AnyDesk.');
    await picker.setInputFiles({name:'second-synthetic.pdf',mimeType:'application/pdf',buffer:Buffer.from('%PDF-1.4\nSynthetic second\n%%EOF')});
    await page.getByText('Ready to send · not analyzed',{exact:true}).waitFor();
    await composer.fill('My unsent attachment draft');
    const quick=page.waitForResponse(r=>r.url().endsWith('/conversation/turns'));
    await page.getByRole('button',{name:'Not sure',exact:true}).click();
    assert.equal((await(await quick).json()).turns.at(-1).attachments.length,0);
    await page.getByText('Ready to send · not analyzed',{exact:true}).waitFor();
    assert.equal(await composer.inputValue(),'My unsent attachment draft');
    await page.route('**/conversation/turns',async route=>{const response=await route.fetch();await new Promise(resolve=>setTimeout(resolve,500));await route.fulfill({response});},{times:1});
    const combined=page.waitForResponse(r=>r.url().endsWith('/conversation/turns'));
    await page.getByRole('button',{name:'Send message',exact:true}).click();
    await composer.fill('A new draft typed during saving');
    const combinedState=await(await combined).json();assert.equal(combinedState.turns.at(-1).attachments.length,1);
    await page.waitForFunction(()=>document.querySelector('#chat-message')?.value==='A new draft typed during saving');
    assert.equal(combinedState.turns.at(-1).text,'My unsent attachment draft');
    const fresh=await browser.newContext({viewport:{width:1280,height:900}}),second=await fresh.newPage();
    await second.goto(base+'/incident/start');
    let created;
    await second.route('**/api/v1/incidents',async route=>{const response=await route.fetch();created=(await response.json()).id;await route.abort();},{times:1});
    await second.getByRole('textbox',{name:'Message CyberSOS'}).fill('A synthetic first story.');
    await second.getByRole('button',{name:'Send message',exact:true}).click();
    await second.getByRole('button',{name:'Retry message',exact:true}).waitFor();
    await second.reload();await second.getByRole('button',{name:'Retry message',exact:true}).waitFor();
    const retried=second.waitForResponse(r=>r.url().endsWith('/conversation/turns'));
    await second.getByRole('button',{name:'Retry message',exact:true}).click();
    const resumed=await(await retried).json();assert.equal(resumed.incident_id,created);assert.equal(resumed.turns.length,1);
    await second.waitForURL(/\/incident\/[^/]+\/conversation$/);
    await fresh.close();
    await page.screenshot({path:'../backend/tmp/phase4-mock-mobile.png',fullPage:true});
    console.log('PASS: actual browser/API/database direct chat, interrupted creation/reload/retry once, correction/resume, owned attachment-only/replay/deletion, artifacts and mobile composer (fake AI)');
  }finally{await browser.close();}
})().catch(error=>{console.error(error);process.exitCode=1;});
